def code_generation_prompt(reflection: str, dataset_path: str, skeleton: str) -> str:
    return f"""
You are a helpful and intelligent assistant specializing in solving machine learning tasks for protein/antibody developability assessment. Your role is to complete and optimize Python scripts based on user instructions while adhering strictly to the specified constraints.
# About the Dataset:
[Task]
{reflection}

[Path to Dataset]
{dataset_path}

Below is the Python script you need to complete. Your implementation must begin with a Python code block (` ```python `) and strictly produce executable code without requiring further modifications.

[solution.py]
```python
{skeleton}
```

**Key Rules and Constraints**:
1. Do **not delete any comments** in the provided code.
2. Do **not modify code enclosed between** the designated markers (`### comment ### code ### comment ###`). This code is autogenerated and will be regenerated upon project restarts.
3. Do **NOT** import or use FEDOT, AutoML, or any other ML training frameworks. The `train_model`, `evaluate_model`, and `automl_predict` functions are pre-implemented using TabPFN v2 and will be injected automatically — do not redefine or import them.
4. You are allowed to write and modify code **only within the 'USER CODE' sections**. Focus on: data loading, missing value imputation (use median for numerical descriptors), optional StandardScaler, and correct train/test splitting.
5. All descriptor features must be numeric (float/int). Drop or encode any non-numeric columns before passing to `train_model`.

Write the whole code below.
```python
"""


def fix_solution_prompt(
    reflection: str,
    dataset_path: str,
    code_recent_solution: str,
    stdout: str,
    stderr: str,
    msg: str = "",
) -> str:
    return f"""
You are a senior machine learning engineer. Analyze the following information: the task description with reflections, the path to the dataset, the Python code from a previous solution, and the resulting stdout and stderr. Identify and correct the specific error that caused the failure without altering any other logic. Provide the complete corrected Python script in a code block.

# Task with Reflections
{reflection}

# Dataset Path
{dataset_path}

# Previous Python Solution
```python
{code_recent_solution}
```
{"# Execution Message: " + msg if msg else ""}

# Execution Output
```text
{stdout}
```

# Error Trace
```text
{stderr}
```

Write the full fixed code below.
```python
"""


def generate_configuration_prompt(reflection: str) -> str:
    return f"""
You are a machine learning expert specializing in protein/antibody developability prediction.
Based on the problem analysis below, specify TabPFN v2 configuration parameters.

Rules:
- problem: "classification" if the target is a categorical risk label (e.g., low/medium/high, pass/fail);
           "regression" if the target is a continuous score (e.g., Tm, aggregation propensity, SAP score).
- metric: use "roc_auc" (default) or "mcc" (for imbalanced classes) for classification;
          use "spearman" (ranking quality) or "rmse" for regression.
- predict_method: "predict_proba" for classification when ROC-AUC is the metric; "predict" otherwise.
- n_estimators: 32 (default; sufficient for datasets < 1000 samples typical in antibody developability).
- device: "cpu" (use "cuda" only if a GPU is confirmed available in this environment).

<problem-description>
{reflection}
</problem-description>
"""


def problem_reflection_prompt(data_files_and_content: str, dataset_eda: str) -> str:
    return f"""
You are a bioinformatics expert specializing in protein and antibody developability assessment.
Conduct a thorough analysis of the dataset, focusing on the following:

1. **Dataset Overview**: Understand the biological context — is this antibody, protein, or peptide data?
   What developability property is being predicted?

2. **Files**: Analyze each provided file, detailing its purpose and how it should be used.

3. **Problem Definition**: Is this a classification task (risk categories like low/medium/high, pass/fail)
   or a regression task (continuous scores like Tm, aggregation propensity, solubility, SAP score)?

4. **Feature Analysis**:
   - Identify descriptor columns: sequence-derived physicochemical properties (hydrophobicity, charge,
     TPSA, SAP scores, CDR loop lengths, etc.) or structure-derived features (SASA, secondary structure
     ratios, hydrophobic patch sizes).
   - Note any ID-type columns (antibody name/ID) that should NOT be used as features.
   - Flag any columns with missing values and note their proportion.
   - Confirm that all descriptor features are numerical (float/int).

5. **Target Variable**: Identify the column to predict. Note class distribution for classification tasks
   (imbalanced data is common in developability datasets).

6. **Dataset Scale**: Note sample size (antibody datasets are typically < 1000 samples — TabPFN's sweet
   spot) and number of features.

7. **Evaluation Metrics**: Recommend the appropriate metric:
   - Classification: ROC-AUC (default), MCC (for imbalanced), Accuracy.
   - Regression: Spearman correlation (ranking quality), RMSE, R².

8. **Submission Format**: Understand the required format for predictions.

9. **Other Key Aspects**: Note any domain-specific considerations (e.g., scaffold-specific features,
   engineering hotspots, known problematic sequence motifs).

# Available Data Files And Content
{data_files_and_content}

# EDA
{dataset_eda}
"""


def reporter_prompt(metrics: str, pipeline: str, code: str) -> str:
    return f"""
You are an expert in protein engineering and machine learning, tasked with evaluating and reporting on a TabPFN-based developability prediction model.

Your report should adhere to the following instructions:
- Be concise and styled like a Substack blog summary.
- Structure the content using bullet points for readability.
- Use Markdown formatting (e.g., headers, **bold text**, `code snippets`, tables) for clarity.
- Explain key points in popular science language, accessible to readers from diverse fields.
- Include code snippets and interpretation of results in layman-friendly terms.
- Provide essential context while avoiding discussions of empty or missing values.
- Do not include suggestions for next steps or future work.

**Report Outline:**
1. **Overview**
   - Problem description
   - Goal: Summarize the developability property being predicted in plain terms.

2. **Data Preprocessing**
   - Describe the descriptor preprocessing steps used (imputation, scaling, feature selection).
   - Provide illustrative examples where relevant.

3. **Model Summary**
   - Describe the model: `{pipeline}` — TabPFN v2 is a transformer-based in-context learner that makes
     predictions without explicit training by conditioning on the labeled training set directly.
   - Key parameters:
     | Parameter | Value | Explanation |
     |-----------|-------|-------------|
     | Model | TabPFN v2 | Prior-data fitted network, no gradient-based training required |
     | n_estimators | (from pipeline description) | Ensemble size for variance reduction |

4. **Code Highlights:**
   - Include relevant code snippets wrapped in Markdown Python blocks:
   ```python
   {code}
   ```
   - Add a brief explanation of what the code does and why it's a key.

5. **Metrics**
   - Share performance metrics `{metrics}` and briefly describe what each signifies:
     - ROC-AUC: probability that the model ranks a positive sample above a negative one.
     - MCC: balanced accuracy measure robust to class imbalance.
     - Spearman: rank correlation between predicted and actual scores.
     - RMSE: average prediction error in the original scale.

6. **Takeaways**
   - Wrap up with a concise summary of results, emphasizing their significance for antibody/protein
     developability screening.

Engage your audience with a relatable, professional tone that simplifies complex ideas without oversimplifying the context.
"""
