# llm:
#   provider: gigachat
#   model_name: GigaChat-2-Max
#   verify_ssl: false
#   profanity_check: false
#   scope: GIGACHAT_API_CORP
#   timeout: 600

llm:
  provider: openai
  model_name: gpt-4o
  base_url: # Add url

langfuse:
  host: # Add host
  user: # Add user

asr:
  chunk_size: 4000
  sleep_time: 0.1
  sampling_rate: 16000

general:
  max_improvements: 2
  recursion_limit: 50
  max_code_execution_time: 3000
  metric: "ROC-AUC"
  dataset: "employee_promotion"
  word_font: 16 
  language: en

fedot:
  provider: gemini
  model_name: gemini-2.0-flash
  base_url: # Add url
  fix_tries: 2
  templates:
    code: "skeleton-simple.py"
    train: "fedot_train.py"
    evaluate: "fedot_evaluate.py"
    predict: "fedot_predict.py"
  predictor_init_kwargs:
    timeout: 1.0

model_overrides:
  llm_code_generator_agent:
    provider: gigachat
    model_name: GigaChat-2-Max