# llm:
#   provider: gigachat
#   model_name: GigaChat-2-Max
#   verify_ssl: false
#   profanity_check: false
#   scope: GIGACHAT_API_CORP
#   timeout: 600

llm:
  provider: openai
  model_name: gpt-4o
  base_url: # Add url

langfuse:
  host: # Add host
  user: # Add user

general:
  max_improvements: 5
  code_generation_config: 'local'
  recursion_limit: 50
  max_code_execution_time: 3000
  prompt_language: "en"

fedot:
  provider: openai
  model_name: gpt-4o
  base_url: # Add url
  fix_tries: 2
  templates:
    code: "skeleton-simple.py"
    train: "fedot_train.py"
    evaluate: "fedot_evaluate.py"
    predict: "fedot_predict.py"
  predictor_init_kwargs:
    timeout: 1.0

model_overrides:
  llm_code_generator_agent:
    provider: gigachat
    model_name: GigaChat-2-Max