# llm:
#   provider: gigachat
#   model_name: GigaChat-2-Max
#   verify_ssl: false
#   profanity_check: false
#   scope: GIGACHAT_API_CORP
#   timeout: 600

llm:
  provider: openai
  model_name: gpt-4o
  base_url: " "

langfuse:
  host: " "
  user: " "

asr:
  chunk_size: 4000
  sleep_time: 0.1
  sampling_rate: 16000

general:
  max_improvements: 2
  recursion_limit: 50
  max_code_execution_time: 3000
  metric: "ROC-AUC"
  dataset: "employee_promotion"
  word_font: 16 
  language: en

model_overrides:
  llm_code_generator_agent:
    provider: gigachat
    model_name: GigaChat-2-Max